### ISSUE TITLE
API returns empty array when valid trips should exist

### ISSUE THREAD

**Issue by piemadd** [naviqore/public-transit-service#134] opened 2024-10-09 03:58 UTC
I've been playing around with this project for a few days and I must say it is very cool and helpful. That being said, I seem to be running into an issue where the API returns no results for what should be a valid route. 

I am using the up to date docker image on the default settings (I messed with them a bit to no avail) and the NYC subway gtfs (http://web.mta.info/developers/data/nyct/subway/google_transit.zip). One of the routes giving me an issue is from GTFS stop R01 (40.775036, -73.912034) to GTFS stop 115 (40.822008, -73.953676).

I've hosted the API publicly and the below links should give a good result, but don't:
- [https://gtfslink.piemadd.com/routing/connections?timeType=DEPARTURE&dateTime=2024-10-13T13:00:00&sourceStopId=R01&targetStopId=115&travelModes=SUBWAY](https://gtfslink.piemadd.com/routing/connections?timeType=DEPARTURE&dateTime=2024-10-13T13:00:00&sourceStopId=R01&targetStopId=115&travelModes=SUBWAY)
- [https://gtfslink.piemadd.com/routing/connections?sourceLatitude=40.775036&sourceLongitude=-73.912034&targetLatitude=40.822008&targetLongitude=-73.953676&travelModes=RAIL&travelModes=SUBWAY](https://gtfslink.piemadd.com/routing/connections?sourceLatitude=40.775036&sourceLongitude=-73.912034&targetLatitude=40.822008&targetLongitude=-73.953676&travelModes=RAIL&travelModes=SUBWAY)

I am quite rusty on JAVA and have no clue how RAPTOR works, but if pointed in the right direction, I can probably try diagnosing the issue further after my work tomorrow.

Best,
Piero

**Comment by munterfi** [comment] 2024-10-14 15:07
Hi @piemadd,

thanks for the positive feedback on the project and for reporting the issue with a running example.

Are these the valid routes you were expecting? [Google Maps](https://maps.app.goo.gl/LJYLyehhTwNYhru26)
![image](https://github.com/user-attachments/assets/b20ce066-b6a5-4cdf-a497-5258c1750117)

@clukas1, I think we need to debug this locally to determine if the issue is with the router or the GTFS dataset.

Best, 
Merlin

**Comment by clukas1** [comment] 2024-10-14 17:58
Hi @piemadd and @munterfi,

I found the issue, the problem was the NY Subway GTFS only specifies transfers between parent stops and not between each individual stops. I've now added some logic in the GTFS to RAPTOR conversion, and this should be fixed now. I will create a pull request later when I've added some tests.

But if you want to check it out now, you can pull my issue branch.

Here the result for:
http://localhost:8080/routing/connections?timeType=DEPARTURE&dateTime=2024-10-13T13:00:00&sourceStopId=R01&targetStopId=115&travelModes=SUBWAY

![image](https://github.com/user-attachments/assets/64212dd6-cd2a-464d-a2b4-a5801a5a520b)

More to follow.

Cheers
Lukas

**Comment by piemadd** [comment] 2024-10-14 22:40
Hey there @munterfi @clukas1, thanks for the quick responses, that was quick! I'll give it a try.

Best,
Piero

**Comment by piemadd** [comment] 2024-10-14 23:46
Tested and working on my end, big thanks to y'all! https://ek0wcws4cooso0w0c084ss0k.piero.digital/routing/connections?timeType=DEPARTURE&dateTime=2024-10-13T13:00:00&sourceStopId=R01&targetStopId=115&travelModes=SUBWAY

**Closed** 2024-10-21 11:02 UTC
Labels: bug
